trigger:
  - main

pool:
  name: Lab4-Self-Hosted

variables:
  system.debug: true  # Enable detailed logs for troubleshooting

steps:
  # Step 1: Install .NET SDK
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'

  # Step 2: Restore NuGet Packages
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  # Step 3: Build the Project
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration Release'

  # Step 4: Publish the Project
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

  # Step 5: Push the Published Artifacts to a Pipeline Artifact
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'drop'

  # Step 6: Deploy via SSH
  - task: SSH@0
    inputs:
      sshEndpoint: 'MySSHConnection'  # Ensure the service connection is correct
      runOptions: 'inline'
      inline: |
        echo "Starting deployment to remote machine..."
        mkdir -p /home/MySSHConnection/deployments/Lab4-CD-WebApp || { echo "Failed to create directory"; exit 1; }
        echo "Directory created successfully."
        scp -r $(Pipeline.Workspace)/drop/* /home/MySSHConnection/deployments/Lab4-CD-WebApp || { echo "File transfer failed"; exit 1; }
        echo "Files transferred successfully."
        ls -la /home/MySSHConnection/deployments/Lab4-CD-WebApp
      failOnStderr: true
