trigger:
  - main  # Trigger pipeline on changes to the 'main' branch

pool:
  name: Lab4-Self-Hosted  # Specify your self-hosted agent pool

steps:
  # Step 1: Use the .NET SDK
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'  # Ensure you're using .NET 8.x as required

  # Step 2: Restore NuGet Packages
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  # Step 3: Build the Project
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration Release'

  # Step 4: Publish the Project into an Artifact
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

  # Step 5: Publish the Artifact for Deployment
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'drop'

  # Step 6: Deploy to Remote Machine using SSH
  - task: SSH@0
    inputs:
      sshEndpoint: 'MySSHConnection'  # Name of your SSH service connection
      runOptions: 'inline'
      inline: |
        # Define the target directory
        mkdir -p /home/MySSHConnection/deployments/Lab4-CD-WebApp
        # Copy files to the target directory
        scp -r $(Pipeline.Workspace)/drop/* /home/MySSHConnection/deployments/Lab4-CD-WebApp
        # Verify deployment (optional)
        ls -la /home/MySSHConnection/deployments/Lab4-CD-WebApp
      failOnStderr: true
